### Task 1
#### 1. Write a function to compute 5/0 and use try/except to catch the exceptions.

In [13]:
def div(numerator,denominator):
    try:
        return numerator/denominator
    except ZeroDivisionError:
        print("Division by zero is not allowed.Try other value for denominator.")

In [14]:
div(5,0)

Division by zero is not allowed.Try other value for denominator.


#### 2. Implement a Python program to generate all sentences where subject is in ["Americans","Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"].

Hint: Subject,Verb and Object should be declared in the program as shown below.

subjects=["Americans ","Indians"]
verbs=["play","watch"]
objects=["Baseball","Cricket"]

In [15]:
def sent(subjects,verbs,objs):
    for sentence in [f'{subj} {verb} {obj}' for subj in subjects for verb in verbs for obj in objs]:
        print(sentence)
      

In [24]:
subjects=["Americans","Indians"] 
verbs=["play","watch"] 
objects=["Baseball","Cricket"]

sent(subjects,verbs,objects)

Americans play Baseball
Americans play Cricket
Americans watch Baseball
Americans watch Cricket
Indians play Baseball
Indians play Cricket
Indians watch Baseball
Indians watch Cricket


### Task 2
#### 1. Write a function so that the columns of the output matrix are powers of the input vector

The order of the powers is determined by the increasing boolean argument.Specifically,when 
increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1.

HINT:Such amatrix with a geometric progression in each row is named for Alexandre-Theophile Vandermonde.

In [17]:
# without using Numpy
def custom_vander(inp_list, N=None, increasing = False):
    
    if N == None : N = len(inp_list)
    if increasing:
        matrix = [[element**power for power in range(0, N)] for element in inp_list]
        print(matrix)
    else:
        matrix = [[element**power for power in range(N-1, -1, -1)] for element in inp_list]
        print(matrix)

In [18]:
custom_vander([1, 2, 3, 5])

[[1, 1, 1, 1], [8, 4, 2, 1], [27, 9, 3, 1], [125, 25, 5, 1]]


In [19]:
import numpy as np
np.vander([1, 2, 3, 5])

array([[  1,   1,   1,   1],
       [  8,   4,   2,   1],
       [ 27,   9,   3,   1],
       [125,  25,   5,   1]])

In [20]:
# with using numpy
def custom_vander_np(inp_list, N=None, increasing = False):
    
    if N == None : N = len(inp_list)
    if increasing:
        matrix = [[element**power for power in range(0, N)] for element in inp_list]
        print(np.row_stack(matrix))
    else:
        matrix = [[element**power for power in range(N-1, -1, -1)] for element in inp_list]
        print(np.row_stack(matrix))

In [21]:
custom_vander_np([1, 2, 3, 5])

[[  1   1   1   1]
 [  8   4   2   1]
 [ 27   9   3   1]
 [125  25   5   1]]


In [22]:
custom_vander_np([1, 2, 3, 5],N=5)

[[  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [625 125  25   5   1]]


In [23]:
custom_vander_np([1, 2, 3, 5],N=5,increasing = True)

[[  1   1   1   1   1]
 [  1   2   4   8  16]
 [  1   3   9  27  81]
 [  1   5  25 125 625]]
