# Assignment

In [1]:
import numpy as np

Q1. Write the NumPy program to create a 2d array with 6 on the border
and 0 inside?

    Expected OutputOriginal array-
    [ [6 6 6 6 6]
     [ 6 6 6 6 6]
     [ 6 6 6 6 6 ]
    [ 6 6 6 6 6 ]
    [ 6 6 6 6 ] ].
    6 on the border and 0 inside in the array-
    [[ 6 6 6 6 6]
    [ 6 0 0 0 6]
    [ 6 0 0 0 6]
    [ 6 0 0 0 6]
    [ 6 6 6 6 6]].

In [5]:
x = np.ones((5,5))
x = x * 6
print(f'Original array -')
print(x)

x[1:-1,1:-1] = 0
print(f'6 on the border and 0 inside in the array- ')
print(x)

Original array -
[[6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]]
6 on the border and 0 inside in the array- 
[[6. 6. 6. 6. 6.]
 [6. 0. 0. 0. 6.]
 [6. 0. 0. 0. 6.]
 [6. 0. 0. 0. 6.]
 [6. 6. 6. 6. 6.]]


Q2. Write the NumPy program to create a 8x8 matrix and fill it with the
checkerboard pattern?
    
    Checkerboard pattern-
    [[3 9 3 9 3 9 3 9]
    [9 3 9 3 9 3 9 3]
    [3 9 3 9 3 9 3 9]
    [9 3 9 3 9 3 9 3]
    [3 9 3 9 3 9 3 9]
    [9 3 9 3 9 3 9 3]
    [3 9 3 9 3 9 3 9]
    [9 3 9 3 9 3 9 3]].

In [7]:
x = np.ones((8,8))
x = x * 3
x[1::2,::2] = 9
x[::2,1::2] = 9
print(x)

[[3. 9. 3. 9. 3. 9. 3. 9.]
 [9. 3. 9. 3. 9. 3. 9. 3.]
 [3. 9. 3. 9. 3. 9. 3. 9.]
 [9. 3. 9. 3. 9. 3. 9. 3.]
 [3. 9. 3. 9. 3. 9. 3. 9.]
 [9. 3. 9. 3. 9. 3. 9. 3.]
 [3. 9. 3. 9. 3. 9. 3. 9.]
 [9. 3. 9. 3. 9. 3. 9. 3.]]


Q3. Write the NumPy program to create an empty and a full array.
 
     Expected Output-
    [[4.45057637e-308 1.78021527e-306 8.45549797e-307 1.37962049e-306]
    [1.11260619e-306 1.78010255e-306 9.79054228e-307 4.45057637e-308]
    [8.45596650e-307 9.34602321e-307 4.94065646e-322 0.00000000e+000]]
    [[6 6 6]
    [6 6 6]
    [6 6 6]]


In [9]:
x_empty = np.empty((3,4))
print(f'Empty Array: ')
print(x_empty)
x_full = np.full((3,3),6)
print('Full Array: ')
print(x_full)
x = np.empty((3,4))
print(x)

Empty Array: 
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Full Array: 
[[6 6 6]
 [6 6 6]
 [6 6 6]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


Q4. Write the NumPy program to convert the values of Centigrade
degrees into the Fahrenheit degrees and the centigrade values are
stored in the NumPy array.
    
    Sample Array -[0, 12, 45.21 ,34, 99.91]
    Expected OutputValues in Fahrenheit degrees-
    [ 0. 12. 45.21 34. 99.91]
    Values in Centigrade degrees-
    [-17.77777778 -11.11111111 7.33888889 1.11111111 37.72777778]

In [10]:
sample_list = [ 0, 12, 45.21 ,34, 99.91]

fa_array = np.array(sample_list)
print("Values in Fahrenheit degrees")
print(fa_array)

ce_array = 5*(fa_array)/9 - 5*32/9
print("Values in Celcius degrees")
print(ce_array)
nl = '\n'
print(f'Values in Fahrenheit degrees {nl} {fa_array}')

Values in Fahrenheit degrees
[ 0.   12.   45.21 34.   99.91]
Values in Celcius degrees
[-17.77777778 -11.11111111   7.33888889   1.11111111  37.72777778]
Values in Fahrenheit degrees 
 [ 0.   12.   45.21 34.   99.91]


Q5. Write the NumPy program to find the real and imaginary parts of an
array of complex numbers?

    Expected OutputOriginal array [ 1.00000000+0.j 0.70710678+0.70710678j]
    Real part of the array-
    [ 1. 0.70710678]
    Imaginary part of the array-
    [ 0. 0.70710678]

In [25]:
first_num = np.sqrt([1+0j])
second_num = np.sqrt([0+1j])
Orig_arr= list(first_num) + list(second_num)
 
print(f'Original array {Orig_arr}')

real_orig_arr = list(first_num.real) + list(second_num.real)
print(f'Real part of the array- {nl} {real_orig_arr}')

imag_orig_arr = list(first_num.imag) + list(second_num.imag)
print(f'Imaginary part of the array- {nl} {imag_orig_arr}')


Original array [(1+0j), (0.7071067811865476+0.7071067811865475j)]
Real part of the array- 
 [1.0, 0.7071067811865476]
Imaginary part of the array- 
 [0.0, 0.7071067811865475]


Q6. Write the NumPy program to test whether each element of a 1-D
array is also present in the second array?

    Expected OutputArray1: [ 0 10 20 40 60]
    Array2: [0, 40]
    Compare each element of array1 and array2
    [ True False False True False]


In [27]:
array1 = np.array([0, 10, 20, 40, 60])
print(f'Array1: {array1}')

array2 = [0, 40]
print(f'Array2: {array2}')

print(f'Compare each element of array1 and array2 {nl} {np.in1d(array1, array2)}')


Array1: [ 0 10 20 40 60]
Array2: [0, 40]
Compare each element of array1 and array2 
 [ True False False  True False]


Q7. Write the NumPy program to find common values between two
arrays?
    
    Expected OutputArray1: [ 0 10 20 40 60]
    Array2: [10, 30, 40]
    Common values between two arrays-
    [10 40]

In [28]:
array1 = np.array([0, 10, 20, 40, 60])
print(f'Array1: {array1}')
array2 = np.array([10,30,40])
print(f'Array2: {array2}')
print(f'Common values between two arrays- {nl} {np.intersect1d(array1,array2)}')

Array1: [ 0 10 20 40 60]
Array2: [10 30 40]
Common values between two arrays- 
 [10 40]


Q8. Write the NumPy program to get the unique elements of an array?

    Expected OutputOriginal array-
    [10 10 20 20 30 30]
    Unique elements of the above array-
    [10 20 30]
    P a g e 14 | 44
    Original array-
    [[1 1]
    [2 3]]
    Unique elements of the above array-
    [1 2 3]

In [30]:
orig_array= np.array([10, 10, 20, 20, 30, 30])
print(f'Original array- {nl} {orig_array}')
print(f'Unique elements of the above array-- {nl} {np.unique(orig_array)}')

orig_array1 = np.array([[1, 1], [2, 3]])
print(f'Original array- {nl} {orig_array1}')
print(f'Unique elements of the above array-- {nl} {np.unique(orig_array1)}')


Original array- 
 [10 10 20 20 30 30]
Unique elements of the above array-- 
 [10 20 30]
Original array- 
 [[1 1]
 [2 3]]
Unique elements of the above array-- 
 [1 2 3]


Q9. Write the NumPy program to find the set exclusive-or of two arrays.
Set exclusive-or will return the sorted, unique values that are in
only one (not both) of the input arrays?

    Array1- [ 0 10 20 40 60 80]
    Array2- [10, 30, 40, 50, 70]
    Unique values that are in only one (not both) of the input arrays-
    [ 0 20 30 50 60 70 80]

In [32]:
array1 = np.array([0, 10, 20, 40, 60, 80])
print(f'Array1 - {array1}')

array2 = [10, 30, 40, 50, 70]
print(f'Array2 - {array2}')

print(f'Unique values that are in only one (not both) of the input arrays- {nl} {np.setxor1d(array1, array2)}')


Array1 - [ 0 10 20 40 60 80]
Array2 - [10, 30, 40, 50, 70]
Unique values that are in only one (not both) of the input arrays- 
 [ 0 20 30 50 60 70 80]


Q10. Write the NumPy program to test if all elements in an array
evaluate to True ?
 
Note: 0 evaluates to False in NumPy

In [33]:
# we use numpy.all to find if elements in all axis of an array evaluate to be true
# https://docs.scipy.org/doc/numpy/reference/generated/numpy.all.html
# Boolean
print(np.all([[True,False],[True,True]]))
print(np.all([[True,True],[True,True]]))

# Integers
print(np.all([10, 20, 0, -50]))
print(np.all([10, 20, -50]))

False
True
False
True


Q11. Write the NumPy program to test whether any array element along
the given axis evaluates to True?
 
Note: 0 evaluates to False in NumPy

In [37]:
# We use numpy.any to find 

print(np.any([[True,False],[False,False]]))
print(np.any([[True,False],[False,False]], axis=0))

print(np.any([[True,True],[True,True]]))
print(np.any([10, 20, 0, -50]))
print(np.any([10, 20, -50]))

True
[ True  True]
[ True  True]
True
True
True


Q12. Write the NumPy program to construct an array by repeating?

    Sample array- [1, 2, 3, 4]
    Expected OutputOriginal array
    [1, 2, 3, 4]
    Repeating 2 times
    [1 2 3 4 1 2 3 4]
    Repeating 3 times
    [1 2 3 4 1 2 3 4 1 2 3 4]

In [38]:
orig_array = [1, 2, 3, 4]
print(f'Original array {nl} {orig_array}')

print(f'Repeating 2 times {nl} {np.tile(orig_array,2)}')

print(f'Repeating 3 times {nl} {np.tile(orig_array,3)}')


Original array 
 [1, 2, 3, 4]
Repeating 2 times 
 [1 2 3 4 1 2 3 4]
Repeating 3 times 
 [1 2 3 4 1 2 3 4 1 2 3 4]


Q13. Write the NumPy program to find the indices of the maximum and
minimum values with the given axis of an array?

    Original array- [1 2 3 4 5 6]
    Maximum Values- 5
    Minimum Values- 0

In [41]:
orig_array = np.array([1,2,3,4,5,6])

print(f'Original array- {orig_array}')
print(f'Maximum Values- {np.argmax(orig_array)}')
print(f'Minimum Values- {np.argmin(orig_array)}')

Original array- [1 2 3 4 5 6]
Maximum Values- 5
Minimum Values- 0


Q14. Write the NumPy program compare two arrays using numpy?

    Array a- [1 2]
    Array b- [4 5]
    a > b
    [False False]
    a >= b
    [False False]
    a < b
    [ True True]
    a <= b
    [ True True]


In [44]:
a = np.array([1, 2])
b = np.array([4, 5])

print(f'Array a- {a}')
print(f'Array b- {b}')

print(f'a>b {nl} {np.greater(a,b)}')


print(f'a>=b {nl} {np.greater_equal(a,b)}')


print(f'a<b {nl} {np.less(a,b)}')


print(f'a<=b {nl} {np.less(a,b)}')


Array a- [1 2]
Array b- [4 5]
a>b 
 [False False]
a>=b 
 [False False]
a<b 
 [ True  True]
a<=b 
 [ True  True]


Q15. Write the NumPy program to sort an along the first, last axis of an
array?

    Sample array- [[2,5],[4,4]]
    Expected OutputOriginal array:
    [[4 6]
    [2 1]]
    Sort along the first axis:
    [[2 1]
    [4 6]]
    Sort along the last axis-
    [[1 2]
    [4 6]]

In [46]:
orig_array = np.array([[4, 6],[2, 1]])

print(f'Original array: {nl} {orig_array}')

print(f'Sort along the first axis: {nl} {np.sort(orig_array,axis=0)}')

print(f'Sort along the last axis: {nl} {np.sort(orig_array,axis=1)}')


Original array: 
 [[4 6]
 [2 1]]
Sort along the first axis: 
 [[2 1]
 [4 6]]
Sort along the last axis: 
 [[4 6]
 [1 2]]


Q16. Write the NumPy program to sort pairs of first name and last name
return their indices (first by last name, then by first name).

    first_names - ( Betsey, Shelley, Lanell, Genesis, Margery )
    last_names - ( Battle, Brien, Plotner, Stahl, Woolum )
    Expected Output-
    [1 3 2 4 0]

In [48]:
first_names =    ('Margery', 'Betsey', 'Shelley', 'Lanell', 'Genesis')
last_names = ('Woolum', 'Battle', 'Plotner', 'Brien', 'Stahl')
x = np.lexsort((first_names, last_names))
print(x)

[1 3 2 4 0]


Q17. Write the NumPy program to get the values and indices of the
elements that are bigger than 10 in the given array?

    Original array-
    [[ 0 10 20]
    [20 30 40]]
    Values bigger than 10 = [20 20 30 40]
    Their indices are (array([0, 1, 1, 1]), array([2, 0, 1, 2]))

In [56]:
orig_array = np.array([[0,10,20],[20,30,40]])
print(f'Original array- {nl} {orig_array}')

print(f'Values bigger than 10 = {orig_array[orig_array>10]}')

x = np.nonzero((orig_array>10))
print(f'Their indices are  {x}')


Original array- 
 [[ 0 10 20]
 [20 30 40]]
Values bigger than 10 = [20 20 30 40]
Their indices are  (array([0, 1, 1, 1], dtype=int64), array([2, 0, 1, 2], dtype=int64))


Q18. Write the NumPy program to find the memory size of a NumPy
array?

    Expected Output128 bytes


In [57]:
import numpy as np
x = np.ones((4,4))
print("%d bytes" % (x.size * x.itemsize) )

128 bytes


## Great Job!